# theme: jekyll-theme-cayman

# Site settings
title: "杨小邪的空中楼阁"
SEOTitle: "杨小邪的空中楼阁"
header-img: "assets/img/home-bg.png"
email: "yangchw@teamsun.com.cn"
description: "拥有的都是侥幸，失去的都是人生"
keyword: "杨小邪的空中楼阁"
url: "https://www.yangxiaoxie.com/"
baseurl: ""


# avatar and Favicon
# avatar: http://7u2ho6.com1.z0.glb.clouddn.com/site-avatar.png
favicon: favicon.png


# Sidebar settings
sidebar: false
sidebar-about-description: ""
sidebar-avatar: /assets/img/avatar.png 


# Featured Tags
featured-tags: true 
featured-condition-size: 1


# SNS settings
RSS: false
weibo_username: false
zhihu_username: false
github_username: moodpo


# Build settings
paginate: 10
plugins: [jekyll-paginate]
# gems: [jekyll-paginate]


# Gitalk
gitalk:
  enable: true
  clientID: f992c0031dec436dd006
  clientSecret: 676c304c2d94731f12eaf60064e700786d224dd2
  repo: yangxiaoxie.com
  owner: TeamSunCloud
  admin: moodpo
  # distractionFreeMode: true
